version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run:
          name: Intall dependencies
          command: yarn install
      - run:
          name: Build projects
          command: yarn build
      - run:
          name: Configure git defaults
          command: git config user.email "dev@cschroeter.net" && git config user.name "Christian Schröter"
      - run:
          name: Release projects
          command: npm run release
