version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn build
      - run:
          name: Configure git defaults
          command: git config user.email "dev@cschroeter.net" && git config user.name "Christian Schröter"
      - run:
          name: release
          command: npm run release || true
